-- Esquema simulado de SUA.mdb
CREATE TABLE Patron (
  REG_PAT VARCHAR(11) PRIMARY KEY,
  RFC_PAT VARCHAR(13),
  NOM_PAT VARCHAR(100),
  DOMICILIO VARCHAR(100),
  MUNICIPIO VARCHAR(50),
  CP VARCHAR(5),
  ENTIDAD VARCHAR(2),
  TELEFONO VARCHAR(20),
  ACTIVIDAD_ECONOMICA VARCHAR(100),
  DELEGACION VARCHAR(3),
  CLASE_RIESGO VARCHAR(3),
  PRIMA_RT DECIMAL(10,5)
);

CREATE TABLE Trabajador (
  NSS VARCHAR(11) PRIMARY KEY,
  RFC VARCHAR(13),
  CURP VARCHAR(18),
  NOMBRE VARCHAR(40),
  AP_PATERNO VARCHAR(40),
  AP_MATERNO VARCHAR(40),
  FECHA_NACIMIENTO DATE,
  SEXO VARCHAR(1),
  TIPO_SALARIO VARCHAR(1),
  SALARIO_DIARIO DECIMAL(10,2),
  REG_PAT VARCHAR(11),
  FECHA_AFILIACION DATE,
  UMF VARCHAR(3),
  TIPO_TRABAJADOR VARCHAR(1),
  PENSIONADO BOOLEAN
);

-- Tablas adicionales
CREATE TABLE Prima_RT (
    REG_PAT VARCHAR(11),
    ANIO INT,
    VALOR DECIMAL(10,5)
);
CREATE TABLE Resultado_ConfrontaBim (
    ID INT PRIMARY KEY
);
CREATE TABLE TablaUMA (
    FECHA DATE,
    VALOR DECIMAL(10,2)
);
CREATE TABLE TablaValINF (
    FECHA DATE,
    VALOR DECIMAL(10,2)
);
CREATE TABLE IndexTablaParametros (
    CLAVE VARCHAR(50) PRIMARY KEY,
    VALOR VARCHAR(200)
);
